export { default as DefaultLayout } from "./DefaultLayout/defaultlayout.component";
export { default as Startlayout } from "./StartLayout/startlayout.component";
export { default as ProfileLayout } from "./ProfileLayout/profilelayout.component";
export { default as SettingLayout } from "./SettingLayout/settinglayout.component";
export { default as TopicLayout } from "./TopicLayout/topiclayout.component";
export { default as AuthenLayout } from "./AuthenLayout/authenlayout.component"
export { default as CreatePostLayout } from "./CreatepostLayout/createpostlayout.component";
export { default as PostLayout } from "./PostLayout/postlayout.component";
export { default as PricingLayout } from "./PricingLayout/pricinglayout.component";